[package]
name = "cargo-workspace-version"
version = "0.0.3"
edition = "2021"
description = "Cargo plugin to update all versions in a workspace"
license-file = "LICENSE"
homepage = "https://avalabs.org"
readme = "README.md"
authors = [
     "Ron Kuris (@rkuris) <ron.kuris@avalabs.org>",
]

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.5", features = ["derive"] }
serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.3"
toml_edit = { version = "0.19.8", features = ["serde"] }
